### ISSUE TITLE
homebrewを用いたclangsayのインストール方法を、README.mdに載せたい

### ISSUE THREAD

**Issue by sasairc** [844196/homebrew-Renge#3]
- 本題
  homebrewを用いたclangsayのインストール方法を、README.mdに載せていいですかね？
- 副題
  clangsay-0.0.5以降は`depends_on`に対して
  `pkg-config`と`glib`を指定したらビルドできるはず。（未確認なのでごめんなさい）
  
  `COWPATH`も、cowsay側のパスを指定して頂ければ
  問題なく`ymd_udon.cow`等のcowfileを共有できるかと思います。
  　
  　
  もし必要であれば、glibやpkg-config抜きでビルドする為のオプションも作りますので
  issueなりtwitterなりで連絡頂けると嬉しいです。

**Comment by 844196** [comment]
@sasairc 

> homebrewを用いたclangsayのインストール方法を、README.mdに載せていいですかね？

現状`0.4`（だったかな）のフォーミュラは上げてありますが、試してみた結果アンインストール時の挙動がおかしいのと、なんか忙しいのでストップ中です。こっちからお願いしてのっけてアレですが、検査が終わるまで保留とさせてください。（たぶん別にチケット切ります）

> clangsay-0.0.5以降はdepends_onに対して
> pkg-configとglibを指定したらビルドできるはず。（未確認なのでごめんなさい）

`0.5`まったく触れてないです...
ビルドもしてないので、帰ったら試してみます。それまで保留ということで。

---

最近お仕事で███████ばっかなのでこっちの███すごい使いやすいゾ

**Comment by sasairc** [comment]
@844196 

> 現状0.4（だったかな）のフォーミュラは上げてありますが、試してみた結果アンインストール時の挙動がおかしいのと、なんか忙しいのでストップ中です。こっちからお願いしてのっけてアレですが、検査が終わるまで保留とさせてください。（たぶん別にチケット切ります）
> 
> 0.5まったく触れてないです...
> ビルドもしてないので、帰ったら試してみます。それまで保留ということで。

おかのした、また時間があるときにでも。

> 最近お仕事で███████ばっかなのでこっちの███すごい使いやすいゾ

それマジ？（bugzillaで頭が止まってて）これもうわかんねえなぁ
ちなみに業務系N○Cソフトの下請けでは、BTSなんてハイテクなものは無くてExcelのみでした（小声）

**Comment by 844196** [comment]
@sasairc 

> ちなみに業務系N○Cソフトの下請けでは、BTSなんてハイテクなものは無くてExcelのみでした（小声）

![bxbzacocmaiomwg png-large](https://cloud.githubusercontent.com/assets/4990822/6598960/4ababa24-c84a-11e4-9a8e-2a95d763df88.png)

今の案件は████████とか███の███（が███ものを検証するお仕事）ですが、███+███████+█████です。████はいいですが、███なり█████が`██████████`な感じで辛い。そこは█████じゃないんかい、と思いました（小並感）。

現在の近況は[ポエム](http://844196.com/post/113340476429)に書いた通りで、友人にも言いましたが「軍事オタクが次の日戦場に投入された」心境です。実際に着手するのは4月に入ってからと考えておいてください。
本Issueはcloseします。

---

真面目なチャットばっかしてると語録が使えなくなった
