### ISSUE TITLE
clangsay概略

### ISSUE THREAD

**Issue by 844196** [844196/homebrew-Renge#4]
0450bdb66227562bd788d79f1d21108a8e11bb8e にて修正実施分
- 依存関係の解決（`0.0.5`より要求の`pkg-config`と`glib`）
- `brew install clangsay`が正しく実行される
  - 以下ディレクトリにファイルが配置展開される
    - `/usr/local/cellar/clangsay/0.0.5/bin/clangsay`
    - `/usr/local/cellar/clangsay/0.0.5/share/cows/*`
    - `/usr/local/share/cows/*`（`cowsay`のcowディレクトリに`yasuna.cow`等が展開される）
- `brew install --zsh-completion clangsay`が正しく実行され、補完が使えるようになる
  - 以下ディレクトリにファイルが配置展開される
    - `/usr/local/cellar/clangsay/0.0.5/_clangsay`
    - `/usr/local/share/zsh/site-functions/_clangsay`
  - `zsh_completion.install`を使用（brew側の仕様いまいち不明）
    - `$fpath`に上記パスを追加してもらう必要がある
    - ただ、brew標準ぽいのでだいたいの人設定済み？

今後、以下の実装・修正を予定
- `--without-cows`オプションの実装
- `--zsh-completion`オプション実行時、`$fpath`に該当ディレクトリを追加する旨を表示

**Comment by 844196** [comment]
@sasairc

![chemineko_2014-11 -10](https://cloud.githubusercontent.com/assets/4990822/6640130/b63ce832-c9d8-11e4-8a3c-176b23d09c82.jpg)

あらためて報告です
0450bdb66227562bd788d79f1d21108a8e11bb8e, fe449e257715da200320d460a56011cb02e6c1ae にて完全な`clangsay`のHomebrewによる導入、および`Readme.md`に沿った2つのオプションを実装しました

## 導入

``` shell-session
$ brew install clangsay
```

`share/cows/`（`cowsay`側）へcowファイルのインストールを行います。`make && make install`と同じです。

## zsh補完関数をインストール

``` shell-session
$ brew install --zsh-completion clangsay
```

zsh補完関数も同時にインストールします。画面上に示されるパスを`$fpath`（環境によって異なる）にユーザーが追加する必要があります。`COWPATH`はどのオプションでも`cowsay`側が指定されます。

## cowファイルを含まずインストール

``` shell-session
$ brew install --without-cows
```

`$(brew --prefix)/cellar/clangsay/<version>/share/clangsay/cows`へは配置されますが、`cowsay`側の`COWPATH`への導入は行いません。

**Comment by sasairc** [comment]
@844196 
![1351262232224](https://cloud.githubusercontent.com/assets/9349287/6640224/23c39036-c9d9-11e4-887c-71b7cc046171.jpg)
おお、有難うございます！
この情報を参考に、早速README.mdを書きます。

**Comment by sasairc** [comment]
@844196 
ブランチを切って書いてみました。
間違っている箇所があれば、指摘して頂けると助かります。

https://github.com/sasairc/clangsay/blob/fix_readme/README.md
