### ISSUE TITLE
brew uninstall clangsayを実行してもcowファイルが削除されない

### ISSUE THREAD

**Issue by 844196** [844196/homebrew-Renge#5]
`cowpath`を指定して

``` ruby
cowpath.install "#{prefix}/share/cows/*"
```

で直りそうな気がする

**Comment by 844196** [comment]
おちんぽには勝てなかったよ...
一応`.install`を使用するように変更

``` ruby
cowpath = "#{HOMEBREW_PREFIX}" + '/share/cows'

if !(build.include?('without-cows'))
    Pathname("#{cowpath}").install Dir["#{prefix}/share/clangsay/cows/*"]
end
```

**Comment by 844196** [comment]
`clangsay`のDSL側を`#{prefix}/share/cows/*`にするテスト

**Comment by 844196** [comment]
![2015-03-14_14-46-41](https://cloud.githubusercontent.com/assets/4990822/6650500/f8030bf4-ca58-11e4-99e4-6e496ad173e4.png)

**Comment by sasairc** [comment]
@844196 
Homebrewが動く実環境が無く、任せっきりですみません。
ありがとうございました！
